services:
  BALD:
    image: quay.io/damajor/bald:latest
    environment:
      - TZ=Europe/Rome
    volumes:
      - /home/mysuser/.audible:/root/.audible
      - /home/mysuser/Audible/lib_history:/audible_history
      - /home/mysuser/Audible/audible_last_sync:/status_file
      - /home/mysuser/Audible/downloads:/audible_dl
      - /home/mysuser/AudioBookShelf/audiobooks:/audiobooks_dest
      - /home/mysuser/BALD/myconfig:/BALD/myconfig
      - /home/mysuser/BALD/tmp:/BALD/tmp